name: bloom_gad_app
description: BLOOM - CvSU GADRC Mobile & Web Application

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  timeago: ^3.6.0
  flutter:
    sdk: flutter

  # UI & Fonts
  google_fonts: ^6.1.0
  percent_indicator: ^4.2.3
  cached_network_image: ^3.3.1
  flutter_animate: ^4.3.0

  # Supabase
  supabase_flutter: ^2.5.6

  # Environment
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.3.2

  # Android features
  gal: ^2.3.0
  share_plus: ^10.0.0
  path_provider: ^2.1.0
  flutter_pdfview: ^1.3.2
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  web: 0.5.1

flutter:
  uses-material-design: true

  assets:
    - assets/config.json