name: bloom_gad_app
description: BLOOM - CvSU GADRC Mobile & Web Application

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  timeago: ^3.6.0
  flutter:
    sdk: flutter

  # UI & Fonts
  google_fonts: ^8.1.0
  percent_indicator: ^4.2.3
  cached_network_image: ^3.3.1
  flutter_animate: ^4.3.0

  # Supabase
  supabase_flutter: ^2.5.6

  # Environment
  flutter_dotenv: ^6.0.1
  jitsi_meet_flutter_sdk: ^10.2.0

  # Android features
  gal: ^2.3.0
  share_plus: ^13.1.0
  path_provider: ^2.1.0
  flutter_file_downloader: 2.1.1
  flutter_pdfview: ^1.3.2
  http: ^1.2.0
  google_sign_in: ^7.2.0
  image_picker: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.13.1
  app_links: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/gad.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/gad.png"

flutter:
  uses-material-design: true

  assets:
    - assets/config.json
    - assets/icons/gad.png